pipeline {
    agent any

    options {
        timeout(time: 40, unit: 'MINUTES')
    }

    parameters {
        string(name: 'GITHUB_CREDENTIAL', defaultValue: 'github_creds', description: 'GitHub credentials id')
        string(name: 'GITHUB_REPO_URL', defaultValue: 'https://github.com/dkojo/updated-java-springboot-cicd.git', description: 'GitHub repository URL')
        string(name: 'GITHUB_BRANCH', defaultValue: 'main', description: 'GitHub branch')

        choice(
            name: 'TERRAFORM_ACTION',
            choices: ['', 'apply', 'destroy'],
            description: 'Terraform action'
        )

        string(
            name: 'AWS_REGION',
            defaultValue: 'us-east-1',
            description: 'AWS region'
        )
    }

    environment {
        AWS_DEFAULT_REGION = "${params.AWS_REGION}"
        AWS_REGION         = "${params.AWS_REGION}"

        // Terraform working directory
        TF_WORKDIR = "terraform/live/prod"
    }

    stages {

        stage("Validate Parameters") {
            steps {
                script {
                    if (!params.TERRAFORM_ACTION?.trim()) {
                        error('TERRAFORM_ACTION is required. Choose apply or destroy.')
                    }
                }
            }
        }

        stage("Checkout Code") {
            steps {
                git branch: "${params.GITHUB_BRANCH}",
                    credentialsId: "${params.GITHUB_CREDENTIAL}",
                    url: "${params.GITHUB_REPO_URL}"
            }
        }

        stage("Verify AWS Role") {
            steps {
                sh '''
                    echo "Checking AWS identity..."
                    aws sts get-caller-identity
                '''
            }
        }

        stage("Terraform Init") {
            steps {
                dir("${TF_WORKDIR}") {
                    sh '''
                        terraform version
                        terraform init
                    '''
                }
            }
        }

        stage("Terraform Plan") {
            steps {
                dir("${TF_WORKDIR}") {
                    sh '''
                        terraform plan -var-file=../../envs/prod.tfvars
                    '''
                }
            }
        }

        stage("Terraform Apply / Destroy") {
            steps {
                dir("${TF_WORKDIR}") {
                    sh """
                        terraform ${params.TERRAFORM_ACTION} \
                        -var-file=../../envs/prod.tfvars \
                        -auto-approve
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished with status: ${currentBuild.currentResult}"
        }
    }
}